### PR TITLE
Samd peripherals

### PR DESCRIPTION
**Pull request by jamesadevine**
This is a PR for a life without mbed on the CircuitPlayground, created mainly for visibility; [codal-samd](https://github.com/lancaster-university/codal-samd/) is used as a support layer instead. [codal-samd](https://github.com/lancaster-university/codal-samd/) also supports the 51.

The positives:

- [X] IR Support
- [X] USB support.
- [X] The timer doesn't break
- [X] Unifies codal and circuitpython by using the same support layer-ish :wink:
- [X] JACDAC works
- [X] I2C works
- [X] analogue in support

Time needs to be invested in testing, writing analogue in functionality, and usb development; I plan to fix I2C in the next couple of hours.

CC @tballmsft @mmoskal @pelikhan @ladyada @tannewt @deanm1278 @jaqster @abchatra

### CODE REVIEW

**Comment by jamesadevine** [comment]
Fixed i2c

**Comment by sabas1080** [comment]
Serial support?

**Comment by jamesadevine** [comment]
@sabas1080 serial is supported, but it is currently implemented using just a [single wire](https://github.com/lancaster-university/codal-samd/blob/jacdac/src/ZSingleWireSerial.cpp).

I don't think it would be too hard to adapt it to a more traditional UART implementation :smile:

**Comment by jamesadevine** [comment]
Analogue in!

**Comment by pelikhan** [comment]
Analog in?

**Comment by jamesadevine** [comment]
Yes for reading the light and temperature sensors.

**Comment by pelikhan** [comment]
Still needs to be implemented right?

**Comment by jamesadevine** [comment]
Not anymore :smile:

**Comment by ladyada** [comment]
awesome :)

**Comment by jamesadevine** [comment]
- [x] USB
- [ ] IR (Might take a little longer, not as straightforward to port that one)

**Comment by jamesadevine** [comment]
- [X] Serial done (just relies on a PR in core)

Just IR left.

**Comment by jamesadevine** [comment]
Oh, one small caveat is that serial only works (currently) on pad 0, will fix this up next time... stay tuned :smile:

**Comment by Jaqster** [comment]
Thanks James!  Great work!  Hey, are you going to be around for BETT?  Maybe we can meet up in person next week?

**Comment by jamesadevine** [comment]
@Jaqster Yes, will mail you my plans 😄 see you soon...

**Comment by jamesadevine** [comment]
- [X] IR

**Comment by jamesadevine** [comment]
Needs retagging and testing

**Pull request merged**
